export const DECORATOR_MODEL = Symbol('DECORATOR_MODEL');
export const DECORATOR_INJECT = Symbol('DECORATOR_INJECT');
export const DECORATOR_ACTION = Symbol('DECORATOR_ACTION');
export const DECORATOR_TRIGGER = Symbol('DECORATOR_TRIGGER');
export const DECORATOR_CONNECTION = Symbol('DECORATOR_CONNECTION');
export const DECORATOR_IS_METHOD = Symbol('DECORATOR_IS_METHOD');
